name: conduit_api
description: conduit
version: 1.0.0

environment:
  sdk: '>=2.18.7 <3.0.0'

dependencies:
  path: ^1.8.0
  conduit: ^4.1.5
  jaguar_jwt: ^3.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
